chore(testing): this is just so that the CI log reveals the exact Java StackTrace that caused the 500 error for the following failure: RulebookControllerTest.rulebookNotFoundExceptionIsHandledByAdviceAndReturns404:206 Status expected:<404> but was:<500>